il-mio-fotoalbum/Models/Foto.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace il_mio_fotoalbum.Models
{
    [Table("Foto")]
    public class Foto
    {

        [Key]public int Id { get; set; }

        [Column("titolo")]
        [Required(ErrorMessage = "Il campo Titolo è obbligatorio")]
        [StringLength(25, ErrorMessage = "Il Titolo non può avere più di 25 caratteri")]
        public string Titolo { get; set; }

        [Column("descrizione")]
        [Required(ErrorMessage = "Il campo Descrizione è obbligatorio")]
        [StringLength(25, ErrorMessage = "La Descrizione non può avere più di 50 caratteri")]
        public string Descrizione { get; set; }

        [Column("immagine")]
        public byte[]? Immagine { get; set; }
        public string ImgSrc => Immagine != null ? $"data:image/jpeg;base64,{System.Convert.ToBase64String(Immagine)}" : "";

        [Column("visibile")]
        public bool Visibile { get; set; }

        //Relazione con IdentityUser
        public long? UserId { get; set; }
        public User? User { get; set; }

        // * to *
        public List<Categoria>? Categorias { get; set; }
        public Foto() { }

        public Foto(string titolo, string descrizione, byte[] immagine, bool visibile)
        {
            this.Titolo = titolo;
            this.Descrizione = descrizione;
            this.Immagine = immagine;
            this.Visibile = visibile;
        }
    }
}

il-mio-fotoalbum/Controllers/CategoriaController.cs
using il_mio_fotoalbum.Data;
using il_mio_fotoalbum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace il_mio_fotoalbum.Controllers
{
    public class CategoriaController : Controller
    {

        //INDEX
        [Authorize(Roles = "ADMIN")]
        public IActionResult Index()
        {
           return View(FotoManger.GetCategorie());
        }


        //CREATE
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            return View();
        }

        
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        public IActionResult Create(Categoria categoria)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", categoria);
            }

            CategoriaManager.InsertCategoria(categoria);
            return RedirectToAction("Index");
        }

        //DELETE
        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            CategoriaManager.DeleteCategoria(id);
            return RedirectToAction("Index");
        }
    }
}

il-mio-fotoalbum/Controllers/FotoController.cs
using il_mio_fotoalbum.Data;
using il_mio_fotoalbum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace il_mio_fotoalbum.Controllers
{
    public class FotoController : Controller
    {

        //INDEX
        [Authorize(Roles = "ADMIN, USER")]
        public IActionResult Index()
        {
            return View(FotoManger.GetAllFoto());
        }


        //SHOW
        [Authorize(Roles = "ADMIN, USER")]
        public IActionResult Show(int id)
        {
            var foto = FotoManger.GetFoto(id);
            if (foto != null)
            {
                return View(foto); 
            }

            return View("Errore");
        }

        //CREATE
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            FotoFormModel model = new FotoFormModel();
            model.Foto = new Foto();
            model.CreaCategorie();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create(FotoFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.CreaCategorie();
                return View("Create", data);
            }

            data.SetImmagine();
            FotoManger.InsertFoto(data.Foto, data.SelectCategorie);
            return RedirectToAction("Index");
        }


        //EDIT
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id)
        {
            var FotoDaModificare = FotoManger.GetFoto(id);

            if (FotoDaModificare == null)
            {
                return View("Errore");
            }
            else
            {
                FotoFormModel model = new FotoFormModel(FotoDaModificare);
                model.CreaCategorie();
                return View(model);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id, FotoFormModel data)
        {
            if(!ModelState.IsValid)
            {
                data.CreaCategorie();
                return View("Update", data);
            }

            data.SetImmagine();
            if (FotoManger.UpdateFoto(id, data.Foto.Titolo, data.Foto.Descrizione, data.Foto.Visibile, data.Foto.Immagine, data.SelectCategorie))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Errore");
            }
        }


        //DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(int id)
        {
            if (FotoManger.DeleteFoto(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Errore");
            }
        }
    }
}

il-mio-fotoalbum/Views/Foto/Create.cshtml
@model FotoFormModel


<div class="container">
    <form class="form" asp-controller="Foto" asp-action="Create" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <strong>Titolo:</strong>
            <input asp-for="Foto.Titolo" class="d-block w-100" />
            <span asp-validation-for="Foto.Titolo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Descrizione:</strong>
            <input asp-for="Foto.Descrizione" class="d-block w-100 is-invalid" />
            <span asp-validation-for="Foto.Descrizione" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Visibilità:</strong>
            <input class="text-start" asp-for="Foto.Visibile" />
            <span asp-validation-for="Foto.Visibile" class="text-danger"></span>
        </div>

        <div class="form-field">
            <img src="@Model.Foto.ImgSrc">
            <label asp-for="ImmagineFile">Immagine:</label>
            <input type="file" asp-for="ImmagineFile" />
        </div>
    
        <div class="mb-3">
            <strong>Categorie:</strong>
     
            @for (int i = 0; i < Model.Categorie.Count; i++)
            {
                <div>
                    <input type="checkbox" name="SelectCategorie" value="@Model.Categorie[i].Value"
                    @(Model.SelectCategorie.Contains(Model.Categorie[i].Value) ? "checked" : "") />
                    @Model.Categorie[i].Text
                </div>
            }
        </div>

       
        <div class="text-end">
            <input type="submit" class="btn btn-small btn-info" value="Inserisci">
        </div>
    </form>
</div>

il-mio-fotoalbum/Views/Foto/Errore.cshtml
<h1>NESSUNA FOTO TROVATA</h1>

il-mio-fotoalbum/Views/Foto/Index.cshtml
@model List<Foto>

@if (User.IsInRole("ADMIN"))
{
    <div class="container-fluid">
        <div class="container">
            <div class="title">
                <h1>Le tue foto</h1>
            </div>

            <div class="input-search">
                <input type="text" id="searchInput" name="search" value="" placeholder="Ricerca foto" />
            </div>

            <div class="input-generici">
                <div class="d-flex my-4">
                    <a href="@Url.Action("Create", "Foto")">
                        <button class="cssbuttons-io-button">
                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="none" d="M0 0h24v24H0z"></path><path fill="currentColor" d="M11 11V5h2v6h6v2h-6v6h-2v-6H5v-2z"></path></svg>
                            <span>Crea</span>
                        </button>
                    </a>

                    <a class="mx-4" href="@Url.Action("Index", "Categoria")">
                        <button class="cssbuttons-io-button">
                            <span>Vai alla sezione categorie</span>
                        </button>
                    </a>

                </div>
            </div>

            <div class="row MyFoto">
                @foreach (var foto in Model)
                {
                    <div class="col-12 col-md-6 col-lg-3 foto-card">
                        <div class="card" style="height: 254px">
                            <a class="mb-4" href="@Url.Action("Show", "Foto", new { id = foto.Id })">
                                <button class="a-index filter-text">@foto.Titolo</button>
                            </a>
                            <div>
                                @if (foto.Visibile)
                                {
                                    <div class="green-dot"></div>
                                }
                                else
                                {
                                    <div class="green-red"></div>
                                }
                            </div>
                            <div class="d-flex">
                                <a href="@Url.Action("Update", "Foto", new { id = foto.Id })">
                                    <button class="btn-53 mx-3">
                                        <div class="original">MODIFICA</div>
                                        <div class="letters">
                                            <span>M</span>
                                            <span>O</span>
                                            <span>D</span>
                                            <span>I</span>
                                            <span>F</span>
                                            <span>I</span>
                                            <span>C</span>
                                            <span>A</span>
                                        </div>
                                    </button>
                                </a>
                            </div>
                            <div>  
                                 <p>
                                    <form asp-controller="Foto" asp-action="Delete" asp-route-id="@foto.Id" method="post">
                                        @Html.AntiForgeryToken()
                                        <button type="button" class="btn btn-danger"
                                                data-bs-toggle="modal"
                                                data-bs-target="#itemModal"
                                                data-id="@foto.Id"
                                                data-action-url="@Url.Action("Delete", "Foto", new { id = foto.Id })">
                                            Elimina
                                        </button>
                                    </form>
                                 </p>
                            </div>
                        </div>
                    </div>
                }
            </div>

        </div>
    </div>
    <div>

</div>
}

<!-- MODALE DI CONFERMA -->
<div id="itemModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Attenzione</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Sei sicuro di voler eliminare questa foto?</p>
                <form id="itemForm" action="" method="post">
                    @Html.AntiForgeryToken()
                    <input type="hidden" id="itemId" name="id" value="" />

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                        <button type="submit" class="btn btn-danger">Elimina</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<script>

    //MODALE
    document.addEventListener('DOMContentLoaded', function () {
        var itemModal = document.getElementById('itemModal');
        var itemForm = document.getElementById('itemForm');
        var itemIdInput = document.getElementById('itemId');

        itemModal.addEventListener('show.bs.modal', function (event) {
            var button = event.relatedTarget;
            var id = button.getAttribute('data-id');
            var actionUrl = button.getAttribute('data-action-url');

            itemIdInput.value = id;
            itemForm.action = actionUrl;
        });
    });


    //FILTRO DI RICERCA
    document.addEventListener("DOMContentLoaded", function () {
        var searchInput = document.getElementById('searchInput');
        searchInput.addEventListener('keyup', function () {
            var filter = this.value.toLowerCase();
            var fotoCards = document.querySelectorAll('.foto-card');

            fotoCards.forEach(function (card) {
                var title = card.querySelector('.filter-text').innerText.toLowerCase();
                if (title.includes(filter)) {
                    card.classList.remove('d-none');
                } else {
                    card.classList.add('d-none');
                }
            });
        });
    });
</script>


<style>
    /* STILE BOTTONE DETTAGLI */
    .btn-53,
    .btn-53 *,
    .btn-53 :after,
    .btn-53 :before,
    .btn-53:after,
    .btn-53:before {
        border: 0 solid;
        box-sizing: border-box;
    }


    .btn-53 {
        -webkit-tap-highlight-color: transparent;
        -webkit-appearance: button;
        background-color: #000;
        background-image: none;
        color: #fff;
        cursor: pointer;
        font-size: 100%;
        line-height: 1.5;
        margin: 0;
        -webkit-mask-image: -webkit-radial-gradient(#000, #fff);
        padding: 0;
    }


    .btn-53:disabled {
         cursor: default;
    }


    .btn-53:-moz-focusring {
         outline: auto;
    }

   .btn-53 svg {
        display: block;
        vertical-align: middle;
   }


   .btn-53 [hidden] {
        display: none;
   }


    .btn-53 {
        border: 1px solid;
        border-radius: 999px;
        box-sizing: border-box;
        display: block;
        font-weight: 700;
        overflow: hidden;
        padding: 10px;
        position: relative;
        text-transform: uppercase;
    }

     
     .btn-53 .original {
         background: #fff;
         color: #000;
         display: grid;
         inset: 0;
         place-content: center;
         position: absolute;
         transition: transform 0.2s cubic-bezier(0.87, 0, 0.13, 1);
     }

   
     .btn-53:hover .original {
         transform: translateY(100%);
     }

   
     .btn-53 .letters {
         display: inline-flex;
     }

    
     .btn-53 span {
         opacity: 0;
         transform: translateY(-15px);
         transition: transform 0.2s cubic-bezier(0.87, 0, 0.13, 1), opacity 0.2s;
     }

   
     .btn-53 span:nth-child(2n) {
         transform: translateY(15px);
     }

 
     .btn-53:hover span {
         opacity: 1;
         transform: translateY(0);
     }

   
     .btn-53:hover span:nth-child(2) {
         transition-delay: 0.1s;
     }

     .btn-53:hover span:nth-child(3) {
         transition-delay: 0.2s;
     }

     .btn-53:hover span:nth-child(4) {
         transition-delay: 0.3s;
     }

     .btn-53:hover span:nth-child(5) {
         transition-delay: 0.4s;
     }

    .btn-53:hover span:nth-child(6) {
         transition-delay: 0.5s;
    }



    .cssbuttons-io-button {
        display: flex;
        align-items: center;
        font-family: inherit;
        font-weight: 500;
        font-size: 16px;
        padding: 0.7em 1.4em 0.7em 1.1em;
        color: white;
        background: #ad5389;
        background: linear-gradient(0deg, rgba(20,167,62,1) 0%, rgba(102,247,113,1) 100%);
        border: none;
        box-shadow: 0 0.7em 1.5em -0.5em #14a73e98;
        letter-spacing: 0.05em;
        border-radius: 20em;
    }

    .cssbuttons-io-button svg {
        margin-right: 6px;
    }

    .cssbuttons-io-button:hover {
       box-shadow: 0 0.5em 1.5em -0.5em #14a73e98;
    }

      
    .cssbuttons-io-button:active {
       box-shadow: 0 0.3em 1em -0.5em #14a73e98;
    }

   
</style>

il-mio-fotoalbum/Views/Foto/Show.cshtml
@using il_mio_fotoalbum.Data;
@model Foto


<div class="container-fluid">
    <div class="container vh-100  d-flex justify-content-center align-items-center flex-column">
        <div class="card">
            <div class="card-image">
                @if (Model.ImgSrc != null)
                {
                    <div class="img">
                        <img src="@Model.ImgSrc" />
                    </div>
                }
                else
                {
                    <h3>La foto non è disponibile</h3>
                }
            </div>
            <div class="card-description">
                
                <p class="text-title"> @Model.Titolo</p>
                <p class="text-body">@Model.Descrizione</p>
                
                 @if (Model.Categorias != null)
                 {
                     @foreach (var categoria in Model.Categorias)
                     {
                        <div class="badge bg-primary">@categoria.Nome</div>
                     }
                 }
                 else
                 {
                     <h6>Nessuna categoria selezionata</h6>
                 }
            </div>
        </div>
    </div>

</div>

</div>

<style>
    .card {
        height: 334px;
        width: 369px;
        position: relative;
        transition: all 0.4s cubic-bezier(0.645, 0.045, 0.355, 1);
        border-radius: 16px;
        box-shadow: 0 0 20px 8px #d0d0d0;
        overflow: hidden;
    }


    .card-image {
        height: 100%;
        width: 100%;
        position: absolute;
        transition: all 1s cubic-bezier(0.645, 0.045, 0.355, 1);
        background: #0a3394;
        background: linear-gradient(to top, #0a3394, #4286f4);
    }


    .card-description {
        display: flex;
        position: absolute;
        gap: .5em;
        flex-direction: column;
        background-color: #f5f5f5;
        color: #212121;
        height: 70%;
        bottom: 0;
        border-radius: 16px;
        transition: all 1s cubic-bezier(0.645, 0.045, 0.355, 1);
        padding: 1rem;
        width: 100%;
    }


    .text-title {
        font-size: 1.3rem;
        font-weight: 700;
    }

    .text-body {
        font-size: 1rem;
        line-height: 130%;
    }


  
    .card:hover .card-description {
        transform: translateY(100%);
    }
</style>

il-mio-fotoalbum/Views/Foto/Update.cshtml
@model FotoFormModel


<div class="container">
    <form class="form" asp-controller="Foto" asp-action="Update" method="post" enctype="multipart/form-data">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <strong>Titolo:</strong>
            <input asp-for="Foto.Titolo" class="d-block w-100" />
            <span asp-validation-for="Foto.Titolo" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <strong>Descrizione:</strong>
            <input asp-for="Foto.Descrizione" class="d-block w-100 is-invalid" />
            <span asp-validation-for="Foto.Descrizione" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Visibilità:</strong>
            <input class="text-start" asp-for="Foto.Visibile" />
            <span asp-validation-for="Foto.Visibile" class="text-danger"></span>
        </div>

        <div class="form-field">
            <img src="@Model.Foto.ImgSrc">
            <label asp-for="ImmagineFile">Immagine:</label>
            <input type="file" asp-for="ImmagineFile" />
        </div>


        <div class="mb-3">
            <strong>Categorie:</strong>

            @for (int i = 0; i < Model.Categorie.Count; i++)
            {
                <div>
                    <input type="checkbox" name="SelectCategorie" value="@Model.Categorie[i].Value"
                    @(Model.SelectCategorie.Contains(Model.Categorie[i].Value) ? "checked" : "") />
                    @Model.Categorie[i].Text
                </div>
            }
        </div>


        <div class="text-end">
            <input type="submit" class="btn btn-small btn-info" value="Modifica">
        </div>
    </form>
</div>