il-mio-fotoalbum/Controllers/FotoController.cs
using il_mio_fotoalbum.Data;
using il_mio_fotoalbum.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace il_mio_fotoalbum.Controllers
{
    public class FotoController : Controller
    {

        //INDEX
        [Authorize(Roles = "ADMIN, USER")]
        public IActionResult Index()
        {
            return View(FotoManger.GetAllFoto());
        }


        //SHOW
        [Authorize(Roles = "ADMIN, USER")]
        public IActionResult Show(int id)
        {
            var foto = FotoManger.GetFoto(id);
            if (foto != null)
            {
                return View(foto); 
            }

            return View("Errore");
        }

        //CREATE
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            FotoFormModel model = new FotoFormModel();
            model.Foto = new Foto();
            model.CreaCategorie();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Create(FotoFormModel data)
        {
            if (!ModelState.IsValid)
            {
                data.CreaCategorie();
                return View("Create", data);
            }

            data.SetImmagine();
            FotoManger.InsertFoto(data.Foto, data.SelectCategorie);
            return RedirectToAction("Index");
        }


        //EDIT
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id)
        {
            var FotoDaModificare = FotoManger.GetFoto(id);

            if (FotoDaModificare == null)
            {
                return View("Errore");
            }
            else
            {
                FotoFormModel model = new FotoFormModel(FotoDaModificare);
                model.CreaCategorie();
                return View(model);
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Update(int id, FotoFormModel data)
        {
            if(!ModelState.IsValid)
            {
                data.CreaCategorie();
                return View("Update", data);
            }

            data.SetImmagine();
            if (FotoManger.UpdateFoto(id, data.Foto.Titolo, data.Foto.Descrizione, data.Foto.Visibile, data.Foto.Immagine, data.SelectCategorie))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Errore");
            }
        }


        //DELETE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "ADMIN")]
        public IActionResult Delete(int id)
        {
            if (FotoManger.DeleteFoto(id))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Errore");
            }
        }
    }
}

il-mio-fotoalbum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - il_mio_fotoalbum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/il_mio_fotoalbum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <h4 class="navbar-brand">Il mio Foto Album</h4>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="@Url.Action("Index", "Foto")">Admin</a>
                        </li>
                        <!-- code omitted -->
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - il_mio_fotoalbum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>